// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoGbpcoMwUCdWiM4HeBgIbpPjyHa_MnSI',
    appId: '1:814847705448:web:460c71c395ff78cc4c16dd',
    messagingSenderId: '814847705448',
    projectId: 'iqra-quize',
    authDomain: 'iqra-quize.firebaseapp.com',
    databaseURL: 'https://iqra-quize-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqra-quize.appspot.com',
    measurementId: 'G-C3ETH9BB3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOGwFI3oiAGh4JximxIxY-1U29Di5j8FE',
    appId: '1:814847705448:android:763bcb04dd8620e84c16dd',
    messagingSenderId: '814847705448',
    projectId: 'iqra-quize',
    databaseURL: 'https://iqra-quize-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqra-quize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHhRtXQUVYUdOAUBsslm1kQMpGQYRQN2g',
    appId: '1:814847705448:ios:3d26db91a4942a1a4c16dd',
    messagingSenderId: '814847705448',
    projectId: 'iqra-quize',
    databaseURL: 'https://iqra-quize-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iqra-quize.appspot.com',
    iosClientId: '814847705448-50dnhm8uj54ngttouuq9uh0rti67hmp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizeAppTeacherStudentModule',
  );
}
